### ISSUE TITLE
Alarm/ Outlets/ assumptions

### ISSUE THREAD

**Issue by 19kirk79** [ActiveByte/homebridge-loxone-connect#1]
Thank you for your fork/ rebuild and keeping the loxone plugin alive!
There have already been versions where the "alarm system" worked and another version where "outlets" worked (thats just optical. Currently they are shown as switches in Home).
Unfortunately no plugin where everything worked so your ambition is highly welcome.
Thanks in advance for your help!

Having the Loxone Miniserver configured via GUI has already been done by other forks. Way more candy than "hacking" the config.json. But the REAL big deal would be to have the assumptions placed in the GUI config. Means that you can choose a supported device type and write the prefix there. Working with assumptions via terminal needs high knowledge and is of course a source of problems.

If you are working in loxforum.com I could share my work because I also started with a fork ;)

**Comment by ActiveByte** [comment]
Thanks for your feedback!
The "outlets" also work but you have to add the switch to the power categorie, forgot to add that to the readme.
Maybe it would be esier to allow the light switch and outlet to also be defined with a prefix.

With assumptions i actually ment that it needs to be defined with giving the Virtual status block a prefix in the config, no terminal needed :) maybe i should name that different!
![image](https://user-images.githubusercontent.com/49819988/119718210-9378ab80-be67-11eb-819d-6be160a7d194.png)

I just made a account on loxforum, you can show me your work!

Thank you very much for your feedback appreciatie it!

**Comment by ActiveByte** [comment]
Also, i'm currently working on the alarm system ;)

**Comment by 19kirk79** [comment]
Good morning,
have you already started a thread to share my work?
A first look how I would love to have it. Currently just at the GUI because I don´t know exactly to "write it back".

<img width="947" alt="Bildschirmfoto 2021-05-27 um 10 01 14" src="https://user-images.githubusercontent.com/11403075/119789254-2f8bcc80-bed3-11eb-8ce4-720207b5a49b.png">

**Comment by ActiveByte** [comment]
Good morning,
Looks good, was thinking about configurable prefix's too!

For the outlet, this is the icon the category needs so it will display as an outlet. I am going to also allow it to be an outlet with the prefix because that's easier to understand.
![image](https://user-images.githubusercontent.com/49819988/119804075-4edd2680-bee0-11eb-8eac-247e19e22028.png)

What KNX Actuators do you use if i may ask?

Alarm System almost done :)

**Comment by 19kirk79** [comment]
"Energy" and "Electricity" have that icon if I switch to English. In German its "Energie" and "Strom" so I guess we have a winner. But what we see is the prefixes were nice because you are able to configure it as you want.
95% of the KNX actuators and sensors are JUNG and I have a couple of MDT.

Great to hear about the alarm system thx! 👍🏻

**Comment by ActiveByte** [comment]
Alarm done, will commit when the prefixes are done.

So for prefixes, one identifier for each type? or an array with differen possible prefixes?
Not sure about this one, i have enough with one but maybe it could come in handy? Would like to hear your opinion about it.

**Comment by ActiveByte** [comment]
Check last commit
