### ISSUE TITLE
Dim Lamps with homebridge-alexa does not work

### ISSUE THREAD

**Issue by Vanixxx** [ActiveByte/homebridge-loxone-connect#10]
Hi all. 
I have homebridge-alexa with homebridge-loxone-connect running. Everything is working as it should via Siri and homebridge. But when I want to dim a light via Alexa, it first dims to the correct value and then always to 100%.
Log file:
`2021-12-18T09:57:47.902Z alexaLocal Emitting Alexa.PowerLevelController`
`[12/18/2021, 10:57:47 AM] [LoxoneWs] [Dimmer] HomeKit - send on/off message to Bad OG: true`
`
[12/18/2021, 10:57:47 AM] [Alexa] PowerLevelController SetPowerLevel 0E:04:8A:85:A2:97 undefined {
  characteristics: [ { aid: 27, iid: 10, value: 53 }, { aid: 27, iid: 9, value: 1 } ]
} null
`
`2021-12-18T09:57:48.155Z hapNodeJSClient Events [{"host":"<ip>","port":53734,"aid":27,"iid":10,"value":53,"status":53},{"host":"<ip>","port":53734,"aid":27,"iid":9,"value":1,"status":1}]`
`2021-12-18T09:57:48.629Z hapNodeJSClient Events [{"host":"<ip>","port":53734,"aid":27,"iid":10,"value":100,"status":100}]`

I have also contacted @NorthernMan54 (homebridge-alexa) who could help here.

**Comment by NorthernMan54** [comment]
@ActiveByte I have seen this type of behavior with other dimmable bulbs before.  And they were setting a bulb to 100% brightness when they saw an on command.  What is the behavior of Luxone bulbs when an on command is received?

in the log above, Alexa is sending a dim to 53 and a turn on command to the bulb, then a couple of seconds later an event is seen where the bulb brightness is set to 100.  It looks like the bulb goes to 100 when it sees an on command?

**Comment by ActiveByte** [comment]
@NorthernMan54 That's true, when you send an on command to a Loxone dimming function it sets the output to 100%

**Comment by NorthernMan54** [comment]
@Vanixxx Does the same issue occur if you use Siri ?

This is from controlling my Hue lamps with Siri, same pattern of dim and on

```
  HAP-NodeJS:Accessory [Howard-Hue 6E78] Processing characteristic set: {"characteristics":[{"aid":10,"iid":11,"value":50},{"aid":10,"iid":10,"value":true}]} +52s
[Hue] Family Room Lamp: homekit brightness changed from 100% to 50%
  HAP-NodeJS:Accessory [Howard-Hue 6E78] Setting Characteristic "On" to value true +2ms
[Hue] : request 2667294: PUT /lights/4/state {"bri":127}
[Hue] : request 2667294: 200 OK
  HAP-NodeJS:EventedHTTPServer [192.168.1.134] Muting event '10.11' notification for this connection since it originated here. +56s
  HAP-NodeJS:Accessory [Howard-Hue 6E78] Setting Characteristic "Brightness" to value 50 +39ms
```

**Comment by Vanixxx** [comment]
Ok, now I'm confused. With Siri the light is also dimmed to 100% (Thought it was working). With the Home app on my iPhone and via Homebridge UI I can dim.
The log just says:
```[12/21/2021, 6:14:14 PM] [LoxoneWs] [Dimmer] HomeKit - send on/off message to Wohnzimmer: true
[12/21/2021, 6:16:03 PM] [LoxoneWs] [Dimmer] HomeKit - send on/off message to Wohnzimmer: true
[12/21/2021, 6:16:52 PM] [LoxoneWs] [Dimmer] HomeKit - send on/off message to Wohnzimmer: true
[12/21/2021, 6:16:52 PM] [LoxoneWs] [Dimmer] HomeKit - send on/off message to Wohnzimmer: true
[12/21/2021, 6:16:55 PM] [LoxoneWs] [Dimmer] HomeKit - send on/off message to Wohnzimmer: true
[12/21/2021, 6:17:08 PM] [LoxoneWs] [Dimmer] HomeKit - send on/off message to Wohnzimmer: true

**Comment by ActiveByte** [comment]
Does the same happen with version 1.1.4?

**Comment by Vanixxx** [comment]
Hi ActiveByte
I have just installed the 1.1.4 again. Unfortunately, dimming via Siri and Alexa does not work. 
Home App and Homebridge UI works.

**Comment by ActiveByte** [comment]
So you have the same issue on that version?

**Comment by Vanixxx** [comment]
yes exactly

**Comment by ActiveByte** [comment]
Very strange, i noticed this week that when i turn on my desk lamp (manually) to set percentage it turn to 100% for a second and then to the set percentage. Could be the same issue, i will further investigate this and let you know! If you have any news let me know.

**Comment by Vanixxx** [comment]
No change.
In my case, unfortunately, it's the other way around. The light dims to the value requested by Alexa for a short time (ms) and then goes to 100%. With Siri, the dimming works without problems.
If I can support with log files or testing, let me know.

**Comment by ActiveByte** [comment]
I finally had time to figure this out i now found how to reproduce this problem and i'm currently working on a fix.

**Comment by NorthernMan54** [comment]
Tks

**Comment by Vanixxx** [comment]
Very good, works for me! Thank you!
However, if I dim from light off immediately to xx%, the light goes to 100%. I guess a power on is sent which makes the light dim to 100%. The second time (when the light is on) dimming works.

**Comment by ActiveByte** [comment]
Hey Thanks! I noticed that too, i’m working on it hope to get a fix out soon 😊
Right after starting the hub the first interaction always sends a 100% command when you turn it on, trying to work around this.
