### ISSUE TITLE
Feature request: support for adaptive lightning

### ISSUE THREAD

**Issue by elmocito** [ActiveByte/homebridge-loxone-connect#12]
Would be great if the plugin would support adaptive lightning in homekit as the homebridge-hue plugin does (using a deconz there with osram garden light poles).

**Comment by ActiveByte** [comment]
Interesting, at the moment i don't have temperature adjustable lights so i can not test this.

**Comment by ActiveByte** [comment]
Hi elmocito,

Since Loxone has its own implementation of this feature, I have no interest in developing this feature.
