### ISSUE TITLE
Assumptions

### ISSUE THREAD

**Issue by 19kirk79** [ActiveByte/homebridge-loxone-connect#15]
Hi there,

has anyone else issues with assumptions, especially with lock?
Unfortunately I don't know when it stopped to work but currently it doesn't.

cheers

**Comment by 19kirk79** [comment]
Am I the only one facing this problem?
In the description is written that the "Lock" has to be a switch. Fine. (I tried switch, I tried button)

Does it have to be in a specific 
1. category
2. symbol
3. anything else

Greetings

**Comment by MichaelPlank** [comment]
I have the same problem.

For me it does not work for the sprinklers anymore. It did work at some time in the past though. Home App just shows Switches instead of sprinklers.

Also tried the Lock with no success. It stays a regular switch.

**Comment by 19kirk79** [comment]
I think it worked with iOS 14 and stopped in September with iOS 15.

**Comment by 19kirk79** [comment]
@ActiveByte are you aware of this issue? Just asking if there will be a solution for it anytime or if its because of ? and not solvable.

**Comment by fan7a** [comment]
Hi, 
i have exactly the same issues with my assumptions for the sprinklers :( are there any updates?

**Comment by MichaelPlank** [comment]
@ActiveByte, I saw some changes in the ItemFactory in this fork, does this maybe fix this issue?
https://github.com/ActiveByte/homebridge-loxone-connect/compare/main...rudyberends:homebridge-loxone-connect:main

**Comment by 19kirk79** [comment]
@MichaelPlank if I see correctly the only difference are the brackets? I change it manually in the itemfactory at one instance (lock) but there is no change after restart. so, if I didn't miss any other change this is not working.

**Comment by MichaelPlank** [comment]
@19kirk79, yes, only the brackets seem to be different. Thx for testing, too bad it does not work.

Can you simply edit the local source code of the npm module to make changes to the plugin? Is there no packaging step or similar required to apply code changes?

**Comment by ruudvdb** [comment]
I have the same issue. I've also removed all aliases from the config and I still cannot the accessory to show up as a lock. It keeps displaying as a switch.

**Comment by ActiveByte** [comment]
With the latest update the problem should be solved.
