### ISSUE TITLE
Fan Support

### ISSUE THREAD

**Issue by Masegi** [ActiveByte/homebridge-loxone-connect#16]
Hi

I have some devices called "Leaf Lüfter" with a message saying "The widget 'Leaf Lüfter' of type Ventilation is an item not handled.".

In docs you write "To make a fan accessory you have to give a switch the prefix "Fan"."

But i dont understand how to achive this, could you help me please?

**Comment by keuninkske** [comment]
never done it myself, but i think you have to go into your loxone config program
and there give it the name 'Fan leaf lufter' instead

with this prefix it should be recognized different by the homebridge loxone plugin

**Comment by Masegi** [comment]
ok thanks, I will give it a try and give feedback.

**Comment by Masegi** [comment]
![WhatsApp Image 2022-02-13 at 22 51 08](https://user-images.githubusercontent.com/5729517/153776704-ca4b3f04-dba2-4619-b4b5-a1943b33366d.jpeg)

ok, we tried renaming it in the loxone app and restarted homebridge, error has changed to "Fan ..." but still same message :(

**Comment by keuninkske** [comment]
hello,

is it possible you are commenting in a repository different then the one you have installed?

looks like you have LoxoneWS installed and here is the loxoneconnect repository

totaly not sure about this from the information i got, but please check it

grtz

**Comment by Masegi** [comment]
ups, sry i will check that :D

**Comment by Masegi** [comment]
Hi, I've checked the device again, but this is shown, so it should be your plugin:
![image](https://user-images.githubusercontent.com/5729517/153850816-817d75ac-b42e-4aee-bef2-c37d50f6d61e.png)

**Comment by ActiveByte** [comment]
Hey @Masegi you did it correctly, will need to check it myself.

**Comment by ActiveByte** [comment]
The current implementation only supports a loxone switch that can be turned on or off and has the Fan icon.
