### ISSUE TITLE
Shutter target position is inverted

### ISSUE THREAD

**Issue by x-sven** [ActiveByte/homebridge-loxone-connect#31]
Hello, it seems to me that the target position between Loxone and Homebridge is opposite. In Homebridge 0% means closed, in Loxone 0% means open. Does that make sense or does it follow a logic?

Best regards 
Sven

**Comment by tt2g89** [comment]
+1

**Comment by x-sven** [comment]
THX; I think I get the point. "plus one" solves the problem, but cause and doubt remain. I'll close the ticket anyway and hope the answer helps the world.

**Comment by tt2g89** [comment]
@x-sven I don’t think that you understood my +1. It means I’m also complaining about that, because it works exactly opposite to the rest of the components, but cannot solve it.
I upvoted 😉
