### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tbollinger63** [ActiveByte/homebridge-loxone-connect#33]
Synology DS218Play, DSM 7

1. Homebridge is installed and works
2. Other plugins work fine
3. Installation of Loxone Connect returns error messages (when installed via plugin UI)
4. Installation via terminal returns minor warnings, no errors.
5. Plugin installed via terminal does not show up in plugin UI.

Questions:
1. How to see the installed plugin in the plugin UI?
2. If not possible, how to configure and start plugin from the terminal?

*Error messages when installed via plugin UI:*

USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save homebridge-loxone-connect@1.4.1

[##################] / reify:es-abstract: timing reifyNode:node_modules/homebridge-lox
> bufferutil@4.0.7 install
> node-gyp-build

gyp ERR! build error | reify:es-abstract: timing reifyNode:node_modules/homebridge-lox
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.180+
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-loxone-connect/node_modules/bufferutil
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-loxone-connect/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2023-03-13T16_55_41_800Z-debug-0.log

Operation failed. Please review log for details.

**Comment by tbollinger63** [comment]
Solved - sorry for the issue. I found the appropriate directory and moved it to the other plugin folders and then it showed up.

**Comment by ActiveByte** [comment]
Hi, no problem!
Glad to see that you were able to solve this issue.
