### ISSUE TITLE
Handling states with loxone

### ISSUE THREAD

**Issue by RolandSM** [ActiveByte/homebridge-loxone-connect#36]
Hello,

is it possible with this plugin, to send for example a humidity value to loxone?
Also I have to set a state from a light FROM loxone?

Is this possible alone with this plugin?

Greets

**Comment by ActiveByte** [comment]
Hi,

This is possible with a [virtual status](https://www.loxone.com/enen/kb/virtual-status/) block.
See the [assumptions](https://github.com/ActiveByte/homebridge-loxone-connect?tab=readme-ov-file#assumptions)
