### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mesu0815** [ActiveByte/homebridge-loxone-connect#8]
Hallo, ich habe auch das Probleme mit dem User wie in einem Probleme hier vorher beschrieben,
Wenn ich den Admin-Benutzer nutze, bekomme ich die folgende Meldung.

[18.12.2002, 15:08:08] [homebridge-loxone-connect] WS: connect [18.12.2002, 15:08:16] [homebridge-loxone-connect] Plattform - Abrufen der ersten Konfiguration von http://192.168.x.x:80/data/LoxApp3.json 
 /homebridge/node_modules/homebridge-loxone-connect/libs/ItemFactory.js:337 const defaultMoodName = factory.platform.alias['DefaultMood'] || "Aus"; ^ TypeError: Eigenschaften von undefiniert können nicht gelesen werden (Lesen von 'DefaultMood') unter Object.moduleexports.Factory.traverseSitemap (/homebridge/node_modules/homebridge-loxone-connect/libs/ItemFactory.js:337:75) bei moduleexports.Factory.parseSitemap (/homebridge/node_modules/homebridge-loxone-connect/libs/ItemFactory.js:55:37) bei Request._callback (/homebridge/node_modules/homebridge-loxone-connect/index.js:142:38) bei Request.self.callback (/homebridge/node_modules/homebridge-loxone-connect/node_modules/request/request.js:185:22) bei Request.emit (Knoten:events:390:28) auf Anfrage.<anonym> (/homebridge/node_modules/homebridge-loxone-connect/node_modules/request/request.js:1154:10) bei Request.emit (Knoten:events:390:28) bei IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-loxone-connect/node_modules/request/request.js:1076:12) bei Object.onceWrapper (Knoten:events:509:28) bei IncomingMessage.emit (Knoten:Ereignisse:402:35) [18.12.2021, 15:08:16] [homebridge-loxone-connect] Kindbrückenprozess beendet [18.12.2021, 15:08:16] [homebridge-loxone-connect] Prozess beendet. Code: 1, Signal: null [18.12.2002, 15:08:23] [homebridge-loxone-connect] Prozess wird neu gestartet... [18.12.2021, 15:08:23] [homebridge-loxone-connect] Kinderbrücke mit PID 1675 gestartet homebridge API-Version: 2.7 [18.12.2021, 15:08:24] Registrierungsplattform 'homebridge-loxone-connect.LoxoneWs' [18.12.2002, 15:08:24] [homebridge-loxone-connect] Homebridge-loxone-connect v1.1.4 untergeordnete Brücke erfolgreich geladen [18.12.2021, 15:08:24] 0 zwischengespeichertes Zubehör aus cachedAccessories geladen.0E295F854437. [18.12.2002, 15:08:24] [homebridge-loxone-connect] Loxone-Konfiguration abrufen. [18.12.2002, 15:08:24] [homebridge-loxone-connect] Plattform - Warten 8 Sekunden, bis der Anfangszustand über WebSocket abgerufen wird. [18.12.2002, 15:08:24] [homebridge-loxone-connect] WS: connect

**Comment by ActiveByte** [comment]
Can you test if the problem still occurs with the latest version of this plugin?

**Comment by mesu0815** [comment]
Jetzt scheint es zu klappen, super. 👍

**Comment by ActiveByte** [comment]
Perfect!
