### ISSUE TITLE
Not able to see temperatures

### ISSUE THREAD

**Issue by daveo2k** [ActiveByte/homebridge-loxone-connect#9]
Unable to pull temperatures into homebridge…is there something specific in Loxone you need to do to enable this?  The temperatures are provided by the Touch and Touch Pure switches rather than dedicated temperature and humidity sensors if that makes a difference?
Any assistance would be great, other than that it’s a great integration!
Dave

**Comment by ActiveByte** [comment]
Hey there,

You have to drag the temperature sensor on the page, after that the reading should show inside the loxone app too.

Hope this helps!

**Comment by daveo2k** [comment]
Sorry that side is already configured, the temperature shows in Loxone and Loxone app and Loxone is controlling the heating based on that for each room…but it’s not showing in Homebridge…

**Comment by ActiveByte** [comment]
Can you send me the startup log of the homebridge plugin?

**Comment by daveo2k** [comment]
Sorry struggling on my phone to look at the logs and it won’t let me copy and paste 🤦‍♂️I’ll attach the proper log tomorrow but for now…
Platform - The widget ‘Heating and Cooling from IRCV2Daytimer is an item not handled.

Dave

**Comment by daveo2k** [comment]
That is filling up quite a bit of the log

**Comment by daveo2k** [comment]
Log attached..
[Loxone Connect startup.txt](https://github.com/ActiveByte/homebridge-loxone-connect/files/7743260/Loxone.Connect.startup.txt)
.

**Comment by daveo2k** [comment]
hi guys, sorry to hassle but any ideas? @ActiveByte ?

**Comment by daveo2k** [comment]
Ben having a play around and the only way i can get the temperature to show in Homebridge is to create a virtual status within Loxone and feed in to that from the temperature sensor...is that how you guys normally do it?  Thats obviously just a read only solution no way to update that from Homekit.

**Comment by ActiveByte** [comment]
Hey @daveo2k sorry for the late reply! When you drag the temperature into the tab, make sure that visualization is enabled, and that ut appears in the Loxone app under the login credentials that you are using for the homebridge plugin

**Comment by ActiveByte** [comment]
I checked this and by default the visualisation is turned off, if you turn it on it should show.

**Comment by daveo2k** [comment]
Hi @ActiveByte am i right in thinking its read only then?  just providing info to homebridge?

**Comment by ActiveByte** [comment]
That’s true, its real only
